[project]
name = "psychopy-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "007", email = "007lookworld@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "psychopy>=2026.2.3",
    "scipy>=1.15.3",
]
